# Generated by Django 4.2.7 on 2024-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="C:\\Users\\Mario\\ProjectMbti\\ProfileBase.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
