# Generated by Django 5.0 on 2024-04-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MBTI", "0003_dimension_question_codepoint_answer_useranswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codepoint",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MBTI.answer"
            ),
        ),
    ]
