# Generated by Django 5.0 on 2024-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MBTI", "0004_alter_codepoint_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Not specified",
                max_length=6,
            ),
        ),
    ]
